#pragma once

// STM Screen specific
#define SNAKE_PART_SIZE_XY (uint16_t)10
#define SNAKE_MAP_OFFSET_Y (uint16_t)0
#define SNAKE_MAP_OFFSET_X (uint16_t)20

#define SCORE_RECT_X_COORD (uint16_t)0
#define SCORE_RECT_Y_COORD (uint16_t)200
#define SCORE_RECT_HEIGHT (uint16_t)40
#define SCORE_RECT_WIDTH  (uint16_t)240 

// Stm snake part colours
#define NONE_COLOUR LCD_COLOR_WHITE
#define SNAKE_PART_COLOUR LCD_COLOR_BLACK
#define SNAKE_MEAL_COLOUR LCD_COLOR_GREEN
#define SNAKE_TRAP_COLOUR LCD_COLOR_RED
#define MEAL_EATEN_COLOUR LCD_COLOR_LIGHTGREEN
#define TRAP_BROKEN_COLOUR LCD_COLOR_WHITE
#define WALL_COLOUR LCD_COLOR_ORANGE

// Score Frame colour
#define SCORE_TEXT_COLOUR LCD_COLOR_ORANGE
#define SCORE_TEST_BG_COLOUR LCD_COLOR_BLACK
#define SCORE_FRAME_COLOUR LCD_COLOR_BLACK
#define SCORE_FILLING_COLOUR LCD_COLOR_BLACK
